package springfundamentals.springboot.persistense.entity;


import jakarta.persistence.*;

import java.util.List;

// @Entity: it defines this class has a Database Entity
@Entity
// @Table: it defines the entity table on database
@Table( name = "categorias")
public class Categoria {

    //@Id: it defines the primary key
    @Id
    //@GeneratedValue: it defines that the primary key its autogenerated
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //@Column: it defines the name of the column associated
    @Column(name = "id_categoria")
    private Integer idCategoria;

    private String descripcion;
    private Boolean estado;

    public List<Producto> getProductos() {
        return productos;
    }

    public void setProductos(List<Producto> productos) {
        this.productos = productos;
    }

    @OneToMany( mappedBy = "categoria") //nombre de la propiedad creada con ManyToOne
    private List<Producto> productos;

    public Integer getIdCategoria() {
        return idCategoria;
    }

    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Boolean getEstado() {
        return estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

}
